export const CATEGORIES = [
    { id: 1, name: "Fresh Fruits", icon: "Apple" },
    { id: 2, name: "Vegetables", icon: "Leaf" },
    { id: 3, name: "Dairy & Eggs", icon: "Milk" },
    { id: 4, name: "Bakery", icon: "ShoppingBag" },
    { id: 5, name: "Pantry", icon: "Package" },
];

export const PRODUCTS = [
    {
        id: 1,
        title: "Organic Red Apples (1 kg)",
        price: 2.99,
        description: "Freshly harvested, crisp organic red apples. Rich in fibre, vitamins and natural antioxidants. Perfect for snacking or baking.",
        category: "Fresh Fruits",
        image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=500&auto=format&fit=crop&q=80",
        rating: 4.8,
        reviews: 214,
        stock: 80,
        discount: 10,
        unit: "kg"
    },
    {
        id: 2,
        title: "Ripe Bananas (Bunch ~6 pcs)",
        price: 1.49,
        description: "Sweet and energising ripe bananas, sourced directly from tropical farms. A great source of potassium and natural energy.",
        category: "Fresh Fruits",
        image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&auto=format&fit=crop&q=80",
        rating: 4.7,
        reviews: 186,
        stock: 120,
        discount: 0,
        unit: "bunch"
    },
    {
        id: 3,
        title: "Juicy Mangoes (Pack of 4)",
        price: 4.99,
        description: "Hand-picked, sun-ripened Alphonso mangoes bursting with tropical sweetness. Best eaten chilled as a dessert or in smoothies.",
        category: "Fresh Fruits",
        image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=500&auto=format&fit=crop&q=80",
        rating: 4.9,
        reviews: 322,
        stock: 50,
        discount: 15,
        unit: "pack"
    },
    {
        id: 4,
        title: "Fresh Strawberries (250g)",
        price: 3.49,
        description: "Plump, garden-fresh strawberries with a perfect balance of sweetness and tartness. Ideal for desserts, smoothies, or eating straight.",
        category: "Fresh Fruits",
        image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=500&auto=format&fit=crop&q=80",
        rating: 4.8,
        reviews: 198,
        stock: 60,
        discount: 0,
        unit: "250g"
    },
    {
        id: 5,
        title: "Baby Spinach Leaves (200g)",
        price: 2.29,
        description: "Tender, pesticide-free baby spinach leaves packed with iron and vitamins. Perfect for salads, smoothies, and stir-fries.",
        category: "Vegetables",
        image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&auto=format&fit=crop&q=80",
        rating: 4.6,
        reviews: 145,
        stock: 90,
        discount: 0,
        unit: "200g"
    },
    {
        id: 6,
        title: "Broccoli Florets (500g)",
        price: 2.79,
        description: "Crisp, vibrant green broccoli florets — a powerhouse of vitamins C and K. Great roasted, steamed or tossed in pastas.",
        category: "Vegetables",
        image: "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=500&auto=format&fit=crop&q=80",
        rating: 4.5,
        reviews: 95,
        stock: 75,
        discount: 5,
        unit: "500g"
    },
    {
        id: 7,
        title: "Cherry Tomatoes (400g)",
        price: 2.99,
        description: "Sweet, bite-sized cherry tomatoes bursting with flavour. A versatile kitchen essential — great in salads, pasta, and on pizza.",
        category: "Vegetables",
        image: "https://images.unsplash.com/photo-1558818498-28c1e002b655?w=500&auto=format&fit=crop&q=80",
        rating: 4.7,
        reviews: 168,
        stock: 100,
        discount: 0,
        unit: "400g"
    },
    {
        id: 8,
        title: "Organic Carrots (1 kg)",
        price: 1.99,
        description: "Crunchy, naturally sweet organic carrots, freshly pulled from the farm. Rich in beta-carotene and fibre.",
        category: "Vegetables",
        image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=500&auto=format&fit=crop&q=80",
        rating: 4.6,
        reviews: 132,
        stock: 110,
        discount: 0,
        unit: "kg"
    },
    {
        id: 9,
        title: "Farm Fresh Eggs (12 pcs)",
        price: 3.29,
        description: "Free-range eggs from happy hens. Rich, golden yolks and creamy whites — perfect for breakfast, baking, and cooking.",
        category: "Dairy & Eggs",
        image: "https://images.unsplash.com/photo-1569288063389-cf2f6a50a3c6?w=500&auto=format&fit=crop&q=80",
        rating: 4.9,
        reviews: 410,
        stock: 200,
        discount: 0,
        unit: "12 pcs"
    },
    {
        id: 10,
        title: "Full-Fat Greek Yoghurt (500g)",
        price: 3.99,
        description: "Thick, creamy and tangy Greek yoghurt — high in protein and probiotics. Enjoy with honey, granola, or as a cooking ingredient.",
        category: "Dairy & Eggs",
        image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&auto=format&fit=crop&q=80",
        rating: 4.7,
        reviews: 235,
        stock: 80,
        discount: 10,
        unit: "500g"
    },
    {
        id: 11,
        title: "Sourdough Artisan Bread",
        price: 4.49,
        description: "Slow-fermented sourdough bread with a crispy crust and soft, chewy crumb. Made fresh daily with organic flour and wild yeast.",
        category: "Bakery",
        image: "https://images.unsplash.com/photo-1585478259715-876acc5be8eb?w=500&auto=format&fit=crop&q=80",
        rating: 4.9,
        reviews: 504,
        stock: 30,
        discount: 0,
        unit: "loaf"
    },
    {
        id: 12,
        title: "Blueberry Muffins (6 pcs)",
        price: 5.49,
        description: "Soft, fluffy muffins bursting with plump blueberries. Baked fresh every morning with real butter and natural ingredients.",
        category: "Bakery",
        image: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=500&auto=format&fit=crop&q=80",
        rating: 4.8,
        reviews: 289,
        stock: 40,
        discount: 0,
        unit: "6 pcs"
    },
    {
        id: 13,
        title: "Extra Virgin Olive Oil (500ml)",
        price: 8.99,
        description: "Cold-pressed, single-origin extra virgin olive oil from Mediterranean groves. Rich, fruity flavour — ideal for dressings and cooking.",
        category: "Pantry",
        image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&auto=format&fit=crop&q=80",
        rating: 4.8,
        reviews: 162,
        stock: 70,
        discount: 0,
        unit: "500ml"
    },
    {
        id: 14,
        title: "Wild Honey (350g)",
        price: 6.99,
        description: "Raw, unfiltered wild honey harvested from forest hives. Deeply aromatic with floral notes — a natural sweetener and superfood.",
        category: "Pantry",
        image: "https://images.unsplash.com/photo-1546552768-9e3a94b38a59?w=500&auto=format&fit=crop&q=80",
        rating: 4.9,
        reviews: 320,
        stock: 55,
        discount: 0,
        unit: "350g"
    },
    {
        id: 15,
        title: "Basmati Rice (2 kg)",
        price: 5.49,
        description: "Aged, long-grain basmati rice with a fragrant aroma and fluffy texture. Perfect for biryanis, pilafs, and everyday cooking.",
        category: "Pantry",
        image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=80",
        rating: 4.7,
        reviews: 278,
        stock: 150,
        discount: 5,
        unit: "2 kg"
    },
    {
        id: 16,
        title: "Fresh Lemons (6 pcs)",
        price: 1.99,
        description: "Bright, zesty lemons with thin, juicy flesh. Packed with vitamin C — use in drinks, salad dressings, marinades, and desserts.",
        category: "Fresh Fruits",
        image: "https://images.unsplash.com/photo-1582287014914-1db2e3d9c776?w=500&auto=format&fit=crop&q=80",
        rating: 4.6,
        reviews: 109,
        stock: 130,
        discount: 0,
        unit: "6 pcs"
    },
];
